### ISSUE TITLE
Remove non-determinism when multiple files have functions with the same mange name

### ISSUE THREAD

**Issue by Xazax-hun** [dkrupp/clang#27]

**Comment by dkrupp** [comment]
We could remove non-determinism in the short term, by not importing those function where we have mangled name clash. This way we would not need to care about analyzing linking commands.

**Comment by dkrupp** [comment]
-debug why we have duplicate lines in the definedFns.txt even though we don't have clashing definitions (see xerces for examples)
-we should only have duplicate mangled names where the source file is different and we have multiple definitions
-in case of duplicate definitions: remove edges from the control flow graph which start out from clashing functions (because we will not import them)
-add a new column into externalFnMap.txt 'import'/'no-import' indicating whether clang should continue importing the definition. Indicate with no-import all functions that have duplicate definition.
