### ISSUE TITLE
rewrite xtu-build,xtu-analyze scripts

### ISSUE THREAD

**Issue by dkrupp** [dkrupp/clang#6]
```
xtu-build <- b build.json> [-p preanalyze-directory] [-j thread number] [-v] 
```
should accept json compilation database as an input http://clang.llvm.org/docs/JSONCompilationDatabase.html
-v verbose mode should print executed clang commands to stdout

```
xtu-analyze <-b build.json> [-p preanalyze-dir] [-o output-directory] [-e enable checker list] [-d disable checker list]  [-j thread number] [-v] <-g build-graph.json>
```

<output-directory> shall contain the generated plist (this will be possible to import using codecheker)

preanalize dir by default is: .xtu
output directory by default: .xtu-out

build graph json is a build dependency graph in the following form:
[[1,2],[5,6]]
meaning that 1st build command must be run before the 2nd and so on.

**Comment by gerazo** [comment]
I have 2 questions for clarification about the build-graph format:
1. Shouldn't it be [[1,2],[5,6]] to be in a proper JSON format?
2. If 2nd command must be run before 1st that is because 2nd unit calls things in first so 2nd depends on 1st not vice-versa. So does the file format notate dependency or execution order?

**Comment by dkrupp** [comment]
1. yes, you are right. array of arrays is the good format. fixed in the issue.
2. maybe dependency order would be clearer [1,2] meaning 1 must be run before the first. issue text changed accordingly.
